BSS/Models/BookingReceived.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Data.Entity;
using System.ComponentModel.DataAnnotations;
using System.Globalization;
using System.Web.Security;

namespace BSS.Models
{

    public class SearchParameterModel1
    {

        [Display(Name = "Search By BookingArrivedEnquiredToDateTime")]
        public string BookingArrivedEnquiredToDateTime
        {
            get;

            set;
        }
        [Display(Name = "Search By BookingArrivedEnquiredFromDateTime")]
        public string BookingArrivedEnquiredFromDateTime
        {
            get;

            set;
        }

        [Display(Name = "and BookingStatus")]
        public string BookingStatus
        {
            get;

            set;
        }

        [Display(Name = "and Agent")]
        public string Agent
        {
            get;

            set;
        }

        [Display(Name = "and Consultant")]
        public string Consultant
        {
            get;

            set;
        }

        [Display(Name = "and Hotel")]
        public string Hotel
        {
            get;

            set;
        }

        public string Format
        {
            get;

            set;
        }

    }

    public class BookingReceived
    {
        // [Key]
        private int m_BookingArrivedId;
        private string m_BookingArrivedEnquiredDateTime;
        private string m_BookingArrivedEnquiredTime;
        private string m_BookingArrivedEnquiredDetails;
        private string m_TravelDate;
        private int m_AgentId;
        private int m_ConsultantId;
        private string m_BookingType;
        private string m_QuotationSendDateTime;
        private string m_QuotationSendTime;
        private string m_TourPlanRefrence;
        private int m_HotelId;
        private string m_BookingStatus;
        private string m_ConfirmationDate;

        [Key]
        public int BookingArrivedId
        {
            get;
            set;
            //  get { return m_BookingArrivedId; }

            //  set { value = m_BookingArrivedId; }
        }


        [DisplayFormat(DataFormatString = "{0:dd'/'MM'/'yyyy}", ApplyFormatInEditMode = true)]

        [Display(Name = "Enq Arvd Date")]
        [Required]
        public DateTime? BookingArrivedEnquiredDateTime
        {
            get;
            set;

            //  get { return m_BookingArrivedEnquiredDateTime; }

            //  set { value = m_BookingArrivedEnquiredDateTime; }
        }

        [Display(Name = "Enq Rcvd Time")]
        [Required]
        [RegularExpression(@"^(0[1-9]|1[0-2]):[0-5][0-9] (am|pm|AM|PM)$", ErrorMessage = "Invalid Time.")]
        public string BookingArrivedEnquiredTime
        {
            get;
            set;

            //get { return m_BookingArrivedEnquiredTime; }

            //set { value = m_BookingArrivedEnquiredTime; }
        }

        [Display(Name = "Enq Details")]
        [Required(ErrorMessage = "Please Enter Enquiry Details")]
        public string BookingArrivedEnquiredDetails
        {

            get;
            set;
            //get { return m_BookingArrivedEnquiredDetails; }

            //set { value = m_BookingArrivedEnquiredDetails; }
        }

        [DisplayFormat(DataFormatString = "{0:dd'/'MM'/'yyyy}", ApplyFormatInEditMode = true)]
        [Display(Name = "Travel Date")]
        public DateTime? TravelDate
        {

            get;
            set;
            ////get { return m_TravelDate; }

            ////set { value = m_TravelDate; }
        }


        [Display(Name = "Agent")]
        [Required(ErrorMessage = "Please Select Agent")]
        public int AgentId
        {

            get;
            set;
            //get { return m_AgentId; }

            //set { value = m_AgentId; }
        }

        [Display(Name = "CNSLT")]
        [Required(ErrorMessage = "Please Select Consultant")]
        public int ConsultantId
        {

            get;
            set;
            ////get { return m_ConsultantId; }

            ////set { value = m_ConsultantId; }
        }


        [Display(Name = "BKNG TYPE")]
        public string BookingType
        {

            get;
            set;
            //get { return m_BookingStatus; }

            //set { value = m_BookingStatus; }
        }

        [DisplayFormat(DataFormatString = "{0:dd'/'MM'/'yyyy}", ApplyFormatInEditMode = true)]
        [Display(Name = "Quot Sent Date")]
        public DateTime? QuotationSendDateTime
        {

            get;
            set;
            //get { return m_QuotationSendDateTime; }

            //set { value = m_QuotationSendDateTime; }
        }

        [Display(Name = "Quot Sent Time")]
        [RegularExpression(@"^(0[1-9]|1[0-2]):[0-5][0-9] (am|pm|AM|PM)$", ErrorMessage = "Invalid Time.")]
        public string QuotationSendTime
        {

            get;
            set;
            //get { return m_QuotationSendTime; }

            //set { value = m_QuotationSendTime; }
        }

        [Display(Name = "TP Ref")]
        public string TourPlanRefrence
        {

            get;
            set;
            //get { return m_TourPlanRefrence; }

            //set { value = m_TourPlanRefrence; }
        }

        [Display(Name = "Hotel")]
        [Required(ErrorMessage = "Please Select Hotel")]
        public int HotelId
        {

            get;
            set;
            //get { return m_HotelId; }

            //set { value = m_HotelId; }
        }

        [Display(Name = "BKNG ST")]
        public string BookingStatus
        {

            get;
            set;
            //get { return m_BookingStatus; }

            //set { value = m_BookingStatus; }
        }

        [DisplayFormat(DataFormatString = "{0:dd'/'MM'/'yyyy}", ApplyFormatInEditMode = true)]
        [RegularExpression(@"^([1-9]|0[1-9]|1[0-9]|2[0-9]|3[0-1])[- / .]([1-9]|0[1-9]|1[0-2])[- / .](1[9][0-9][0-9]|2[0][0-9][0-9])$", ErrorMessage = "Invalid Date.")]
        [Display(Name = "Date CF")]
        public DateTime? ConfirmationDate
        {

            get;
            set;
            //get { return m_ConfirmationDate; }

            //set { value = m_ConfirmationDate; }
        }



        public BookingReceived() { }

        public BookingReceived(int bookingarrivedId, string bookingarrivedenquireddatetime, string bookingarrivedenquiredtime, string bookingarrivedenquireddetails,
            string traveldate, int agentId, int consultantId, string bookingtype, string quotationsenddatetime, string quotationsendtime, string tourplanrefrence,
            int hotelId, string bookingstatus, string confirmationdate)
        {
            m_BookingArrivedId = bookingarrivedId;
            m_BookingArrivedEnquiredDateTime = bookingarrivedenquireddatetime;
            m_BookingArrivedEnquiredTime = bookingarrivedenquiredtime;
            m_BookingArrivedEnquiredDetails = bookingarrivedenquireddetails;
            m_TravelDate = traveldate;
            m_AgentId = agentId;
            m_ConsultantId = consultantId;
            m_BookingType = bookingtype;
            m_QuotationSendDateTime = quotationsenddatetime;
            m_QuotationSendTime = quotationsendtime;
            m_TourPlanRefrence = tourplanrefrence;
            m_HotelId = hotelId;
            m_BookingStatus = bookingstatus;
            m_ConfirmationDate = confirmationdate;

        }

        public virtual HotelDetails HotelDetail { get; set; }

        public virtual AgentDetails AgentDetail { get; set; }

        public virtual ConsultantDetails ConsultantDetail { get; set; }

    }

}

BSS/Controllers/BookingReceivedController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Transactions;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using DotNetOpenAuth.AspNet;
using Microsoft.Web.WebPages.OAuth;
using WebMatrix.WebData;
using BSS.Filters;
using BSS.Models;
using System.Data.Entity;
using System.Data;
using System.IO;
using Microsoft.Reporting.WebForms;
using PagedList;
using System.Web.Mvc.Ajax;


namespace BSS.Controllers
{
    public class BookingReceivedController : Controller
    {
        private BSSDbContext db = new BSSDbContext();

        //
        // GET: /BookingReceived/

        public ViewResult Index1(string searchString)
        {
            searchString = DateTime.Now.ToString("dd/MM/yyyy");
            IFormatProvider theCultureInfo = new System.Globalization.CultureInfo("en-GB", true);
            DateTime BookingArrivedEnquiredDateTime1 = DateTime.Parse(searchString, theCultureInfo);
            var value3 = from ba in db.BookingReceiveds
                         where (ba.BookingArrivedEnquiredDateTime) == BookingArrivedEnquiredDateTime1
                         select ba;
            return View(value3);

        }



        public ViewResult Pending(string searchString, string searchString1, string searchString2)
        {
            searchString = DateTime.Now.AddDays(-1).ToString("dd'/'MM'/'yyyy");
            searchString1 = DateTime.Now.ToString("dd'/'MM'/'yyyy");
            IFormatProvider theCultureInfo = new System.Globalization.CultureInfo("en-GB", true);
            DateTime BookingArrivedEnquiredDateTime1 = DateTime.Parse(searchString, theCultureInfo);
            DateTime BookingArrivedEnquiredDateTime2 = DateTime.Parse(searchString1, theCultureInfo);
            searchString2 = "--";
            var data1 = db.BookingReceiveds.Where(x => x.BookingStatus == searchString2
                            && x.BookingArrivedEnquiredDateTime == BookingArrivedEnquiredDateTime1
                            || x.BookingStatus == searchString2
                            && x.BookingArrivedEnquiredDateTime != BookingArrivedEnquiredDateTime2).ToList();
            return View(data1.OrderBy(ab => ab.BookingArrivedEnquiredDateTime));
        }



        [HttpGet]

        public ActionResult Report(string sortOrder, int? page)
        {
            ViewBag.CurrentSort = sortOrder;
            var rp = from s in db.BookingReceiveds
                     select s;
            switch (sortOrder)
            {
                case "Name_desc":
                    rp = rp.OrderByDescending(s => s.BookingArrivedId);
                    break;
                default:
                    rp = rp.OrderBy(s => s.BookingArrivedId);
                    break;
            }
            int pageSize = 15;
            int pageNumber = (page ?? 1);
            return View(rp.ToPagedList(pageNumber, pageSize));
        }

        //public ActionResult BookingArrived()
        //{
        //    using (BSSDbContext db = new BSSDbContext())
        //    {
        //        var v = db.BookingArriveds.ToList();
        //        return View(v);
        //    }
        //}

        public ActionResult Report1(string id)
        {
            //LocalReport lr = new LocalReport();
            //string path = Path.Combine(Server.MapPath("~/Report"), "ReportBookingArrived.rdlc");
            //if (System.IO.File.Exists(path))
            //{
            //    lr.ReportPath = path;
            //}
            //else
            //{
            //    return View("Index1");
            //}
            //List<BookingArrived> cm = new List<BookingArrived>();
            //using (BSSDbContext dc = new BSSDbContext())
            //{

            //    cm = dc.BookingArriveds.ToList();

            //}
            //ReportDataSource rd = new ReportDataSource("DataSet1", cm);
            //lr.DataSources.Add(rd);
            //string reportType = id;
            //string mimeType;
            //string encoding;
            //string fileNameExtension;



            //string deviceInfo =

            //"<DeviceInfo>" +
            //"  <OutputFormat>" + id + "</OutputFormat>" +
            //"  <PageWidth>17in</PageWidth>" +
            //"  <PageHeight>10in</PageHeight>" +
            //"  <MarginTop>0.5in</MarginTop>" +
            //"  <MarginLeft>1.2in</MarginLeft>" +
            //"  <MarginRight>0.2in</MarginRight>" +
            //"  <MarginBottom>0.5in</MarginBottom>" +
            //"</DeviceInfo>";

            //Warning[] warnings;
            //string[] streams;
            //byte[] renderedBytes;

            //renderedBytes = lr.Render(
            //    reportType,
            //    deviceInfo,
            //    out mimeType,
            //    out encoding,
            //    out fileNameExtension,
            //    out streams,
            //    out warnings);


            //return File(renderedBytes, mimeType);
            LocalReport localReport = new LocalReport();
            localReport.ReportPath = Server.MapPath("~/Reports/BookingReceivedReport.rdlc");
            ReportDataSource reportDataSource = new ReportDataSource();
            reportDataSource.Name = "DataSet1";
            var BookingArrivedDatefilterList = from ba in db.BookingReceiveds
                                               join ag in db.AgentDetails on ba.AgentId equals ag.AgentId
                                               join cn in db.ConsultantDetails on ba.ConsultantId equals cn.ConsultantId
                                               join ht in db.HotelDetails on ba.HotelId equals ht.HotelId
                                               select new
                                               {
                                                   ba.BookingArrivedId,
                                                   ba.BookingArrivedEnquiredDateTime,
                                                   ba.BookingArrivedEnquiredTime,
                                                   ba.BookingArrivedEnquiredDetails,
                                                   ba.TravelDate,
                                                   ba.AgentDetail.AgentName,
                                                   ba.ConsultantDetail.ConsultantName,
                                                   ba.BookingType,
                                                   ba.QuotationSendDateTime,
                                                   ba.QuotationSendTime,
                                                   ba.TourPlanRefrence,
                                                   ba.HotelDetail.HotelName,
                                                   ba.BookingStatus,
                                                   ba.ConfirmationDate
                                               };


            reportDataSource.Value = BookingArrivedDatefilterList.ToList();

            localReport.DataSources.Add(reportDataSource);

            string reportType = id;
            // string Parameter = bookingarriveddate;
            string mimeType;
            string encoding;
            string fileNameExtension;



            string deviceInfo =

               "<DeviceInfo>" +
               "  <OutputFormat>" + id + "</OutputFormat>" +
               "  <PageWidth>17in</PageWidth>" +
               "  <PageHeight>10in</PageHeight>" +
               "  <MarginTop>0.5in</MarginTop>" +
               "  <MarginLeft>1.2in</MarginLeft>" +
               "  <MarginRight>0.2in</MarginRight>" +
               "  <MarginBottom>0.5in</MarginBottom>" +
               "</DeviceInfo>";

            Warning[] warnings;
            string[] streams;
            byte[] renderedBytes;

            renderedBytes = localReport.Render(
                reportType,
                deviceInfo,
                out mimeType,
                out encoding,
                out fileNameExtension,
                out streams,
                out warnings);


            return File(renderedBytes, mimeType);
        }


        public ActionResult Details(int id = 0)
        {
            BookingReceived bookingreceived = db.BookingReceiveds.Find(id);
            if (bookingreceived == null)
            {
                return HttpNotFound();
            }
            return View(bookingreceived);
        }

        public ActionResult Create()
        {
            ViewBag.HotelDetails = db.HotelDetails.ToList();
            ViewBag.AgentDetails = db.AgentDetails.ToList();
            ViewBag.ConsultantDetails = db.ConsultantDetails.ToList();
            return View("Create");
        }

        [HttpPost]
        public ActionResult Create(BookingReceived bookingreceived)
        {
            if (ModelState.IsValid)
            {
                db.BookingReceiveds.Add(bookingreceived);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.HotelDetails = db.HotelDetails.ToList();
            ViewBag.AgentDetails = db.AgentDetails.ToList();
            ViewBag.ConsultantDetails = db.ConsultantDetails.ToList();

            return View(bookingreceived);
        }

        public ActionResult Edit(int id = 0)
        {


            BookingReceived bookingreceived = db.BookingReceiveds.Find(id);
            if (bookingreceived == null)
            {
                return HttpNotFound();
            }
            ViewBag.HotelId = new SelectList(db.HotelDetails, "HotelId", "HotelName", bookingreceived.HotelId);
            ViewBag.AgentId = new SelectList(db.AgentDetails, "AgentId", "AgentName", bookingreceived.AgentId);
            ViewBag.ConsultantId = new SelectList(db.ConsultantDetails, "ConsultantId", "ConsultantName", bookingreceived.ConsultantId);
            return View(bookingreceived);
        }

        [HttpPost]
        public ActionResult Edit(BookingReceived bookingreceived)
        {
            if (ModelState.IsValid)
            {

BSS/Views/BookingReceived/Report.cshtml
@model PagedList.IPagedList<BSS.Models.BookingReceived>
@using PagedList.Mvc;
<link href="~/Content/PagedList.css" rel="stylesheet" type="text/css" />
@{
    ViewBag.Title = "Report";
    Layout = "~/Views/Shared/_Layout.cshtml";
    Dictionary<string, string> dictionary = new Dictionary<string, string>();
    dictionary.Add("--", "--");
    dictionary.Add("BookingArrivedReceivedDate", "BookingArrivedEnquiredDateTime");
    //dictionary.Add("EnquiryTimeReceived", "BookingArrivedEnquiredDateTime");
    dictionary.Add("EnquiryDetails", "BookingArrivedEnquiredDetails");
    dictionary.Add("TravelDate", "TravelDate");
    dictionary.Add("Agent", "AgentName");
    dictionary.Add("Consultant", "ConsultantName");
    dictionary.Add("BookingType", "BookingType");
    dictionary.Add("QuotationSendDateTime", "QuotationSendDateTime");
    //dictionary.Add("QuotationSendDateTime", "QuotationSendDateTime");
    dictionary.Add("TourPlanRefrence", "TourPlanRefrence");
    dictionary.Add("Hotel", "HotelName");
    dictionary.Add("BookingStatus", "BookingStatus");
    dictionary.Add("DateConfirmed", "ConfirmationDate");
    SelectList list = new SelectList(dictionary, "value", "key");
}
<h2>
    Report</h2>
@using (Html.BeginForm("Report", "BookingReceived", FormMethod.Post))
{    
    <p>
        SearchBy: @Html.DropDownList("SearchBy", list)
        @Html.TextBox("searchString")
        <input type="submit" value="Search" />
    </p> 
}
@{
    <div class="table-responsive">
        <table class="table table-striped table-hover">
            <thead>
                <tr>
                    <th style="text-align: center">
                       Enq Arvd Date
                           @* @Html.DisplayNameFor(model => model.BookingArrivedEnquiredDateTime)*@
                        </th>
                        <th style="text-align: center">
                        Enq Rcvd Time 
                           @* @Html.DisplayNameFor(model => model.BookingArrivedEnquiredTime)*@
                        </th>
                         <th style="text-align: center">
                        Quot Sent Date 	
                         @*   @Html.DisplayNameFor(model => model.QuotationSendDateTime)*@
                        </th>
                        <th style="text-align: center">
                        Quot Sent Time
                           @* @Html.DisplayNameFor(model => model.QuotationSendTime)*@
                        </th>
                        <th style="text-align: center">
                        Enq Details 
                           @* @Html.DisplayNameFor(model => model.BookingArrivedEnquiredDetails)*@
                        </th>
                        <th style="text-align: center">
                        Travel Date
                            @*@Html.DisplayNameFor(model => model.TravelDate)*@
                        </th>
                        <th style="text-align: center">
                         Agent
                           @* @Html.DisplayNameFor(model => model.AgentId)*@
                        </th>
                        <th style="text-align: center">
                          CNSLT
                       @*     @Html.DisplayNameFor(model => model.ConsultantId)*@
                        </th>
                           <th style="text-align: center">
                        BKNG TYPE
                            @*@Html.DisplayNameFor(model => model.BookingType)*@
                        </th>
                        <th style="text-align: center">
                        TP Ref
                            @*@Html.DisplayNameFor(model => model.TourPlanRefrence)*@
                        </th>
                        <th style="text-align: center">
                        Hotel
                           @* @Html.DisplayNameFor(model => model.HotelId)*@
                        </th>
                        <th style="text-align: center">
                        BKNG ST
                            @*@Html.DisplayNameFor(model => model.BookingStatus)*@
                        </th>
                        <th style="text-align: center">
                        Date CF	
                            @*@Html.DisplayNameFor(model => model.ConfirmationDate)*@
                        </th>
                     @*   <th>
                        Action
                        </th>*@
                    @*<th></th>*@
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.BookingArrivedEnquiredDateTime)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.BookingArrivedEnquiredTime)
                        </td>
                          <td>
                            @Html.DisplayFor(modelItem => item.QuotationSendDateTime)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.QuotationSendTime)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.BookingArrivedEnquiredDetails)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.TravelDate)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.AgentDetail.AgentName)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.ConsultantDetail.ConsultantName)
                        </td>
                          <td>
                            @Html.DisplayFor(modelItem => item.BookingType)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.TourPlanRefrence)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.HotelDetail.HotelName)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.BookingStatus)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.ConfirmationDate)
                        </td>
                        @*   <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.BookingArrivedId }) |
            @Html.ActionLink("Details", "Details", new { id=item.BookingArrivedId }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.BookingArrivedId })
        </td>*@
                    </tr>
                }
            </tbody>
        </table>
         Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) of @Model.PageCount
        @Html.PagedListPager(Model, page => Url.Action("Report", new { page, sortOrder = ViewBag.CurrentSort}))
    </div>
}
<div style="padding: 10px; border: 1px solid black">
    <div>
        <a href="@Url.Action("Report1", new { id = "PDF" })">Click here to Get Report in PDF
            Format</a></div>
    <br />
    <div>
        <a href="@Url.Action("Report1", new { id = "Excel" })">Click here to Get Report in Excel
            Format</a></div>
    <br />
    <div>
        <a href="@Url.Action("Report1", new { id = "Word" })">Click here to Get Report in Word
            Format</a></div>
    <br />
    <div>
        <a href="@Url.Action("Report1", new { id = "Image" })">Click here to Get Report in Image
            Format</a></div>
</div>

BSS/Views/BookingReceived/ReportViewer.cshtml
@model BSS.Models.SearchParameterModel1
@{
    ViewBag.Title = "Custom Report Viewer";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@Scripts.Render("~/bundles/jqueryui")

<script type="text/javascript">
    $(function () {
        $("#area1").find("#BookingArrivedEnquiredToDateTime").datepicker();
        $("#area2").find("#BookingArrivedEnquiredFromDateTime").datepicker();
    });
</script>


<script type="text/javascript">
</script>
<hgroup class="title">
    <h1>@ViewBag.Title</h1>
</hgroup>

<section id="ReportViewer">
    <h4>Custom Report.</h4>
    @using (Html.BeginForm(new { ReturnUrl = ViewBag.ReturnUrl }))
    {
          <link href="../../Content/themes/base/jquery.ui.all.css" rel="stylesheet" type="text/css" />
    <script src="../../Scripts/jquery-1.8.0.js" type="text/javascript"></script>
    <script src="../../Scripts/jquery.ui.core.js" type="text/javascript"></script>
    <script src="../../Scripts/jquery.ui.widget.js" type="text/javascript"></script>
    <script src="../../Scripts/jquery.ui.datepicker.js" type="text/javascript"></script>
    
    <link href="../../Content/demos.css" rel="stylesheet" type="text/css" />
        @Html.AntiForgeryToken()
        @Html.ValidationSummary(true)


        <fieldset>
            <legend>Report 1</legend>
            <ol>
                <li>
                 <div id="area1" class="area1">
                   Booking Arrived Enquired To Date
                  
                    @Html.TextBoxFor(m => m.BookingArrivedEnquiredToDateTime)
                    @Html.ValidationMessageFor(m => m.BookingArrivedEnquiredToDateTime)
                    </div>
                     <div id="area2" class="area1">
                    Booking Arrived Enquired From Date
                    @Html.TextBoxFor(m => m.BookingArrivedEnquiredFromDateTime)
                    @Html.ValidationMessageFor(m => m.BookingArrivedEnquiredFromDateTime)
                    </div>
                </li>
            </ol>
            <input type="submit" id="btnSubmit" value="View Report" />
        </fieldset>
    }
</section>
@if (Model != null)
{
    <section class="social" id="ReportDisplayPanel">
        <h4>Report Viewer Section.</h4>
        <div>
        @Html.ActionLink("Download Report in PDF Format", "DownloadReport", new { bookingarrivedrequesttodatetime = Model.BookingArrivedEnquiredToDateTime, bookingarrivedrequestfromdatetime = Model.BookingArrivedEnquiredFromDateTime, format = "PDF" })
        </div>
        <br />
        <div>
        @Html.ActionLink("Download Report in Excel Format", "DownloadReport", new { bookingarrivedrequesttodatetime = Model.BookingArrivedEnquiredToDateTime, bookingarrivedrequestfromdatetime = Model.BookingArrivedEnquiredFromDateTime, format = "Excel" })
        </div>
       
        <div>
        <img src="@Url.Action("GenerateAndDisplayReport", "BookingReceived", new { bookingarrivedrequesttodatetime = Model.BookingArrivedEnquiredToDateTime, bookingarrivedrequestfromdatetime = Model.BookingArrivedEnquiredFromDateTime, format = Model.Format })"   />
        </div>
        <br />
    </section>
}
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}