BSS/Controllers/AdminUserController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Transactions;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using DotNetOpenAuth.AspNet;
using Microsoft.Web.WebPages.OAuth;
using WebMatrix.WebData;
using BSS.Filters;
using BSS.Models;
using System.Data.Entity;
using System.Data;

namespace BSS.Controllers
{
    public class AdminUserController : Controller
    {
        private BSSDbContext db = new BSSDbContext();

        //
        // GET: /AdminUser/


        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Login(AdminUser model, string returnUrl)
        {
            // Lets first check if the Model is valid or not
            if (ModelState.IsValid)
            {
                using (BSSDbContext db = new BSSDbContext())
                {
                    if (db.AdminUsers == null)
                    {
                        if (ModelState.IsValid)
                        {

                            if (model.UserName == "Admin" && model.Password == "1234")
                            {
                                FormsAuthentication.SetAuthCookie(model.UserName, false);
                                return RedirectToAction("About", "Home");
                            }
                            {
                                ModelState.AddModelError("", "Invalid Username or Password");
                            }
                        }

                        return View(model);

                    }
                    else
                    {
                        string username = model.UserName;
                        string password = model.Password;



                        bool userValid = db.AdminUsers.Any(user => user.UserName == username && user.Password == password);


                        if (userValid)
                        {

                            FormsAuthentication.SetAuthCookie(username, false);
                            if (Url.IsLocalUrl(returnUrl) && returnUrl.Length > 1 && returnUrl.StartsWith("/")
                                && !returnUrl.StartsWith("//") && !returnUrl.StartsWith("/\\"))
                            {
                                return Redirect(returnUrl);
                            }
                            else
                            {
                                return RedirectToAction("About", "Home");
                            }
                        }
                        else
                        {
                           // ViewBag.UserTypes = db.UserTypes.ToList();
                            ModelState.AddModelError("", "Enter Valid UserName and Password");
                        }
                    }
                }
            }

            // If we got this far, something failed, redisplay form
            return View(model);
        }


        public ActionResult Login()
        {
            return View();
        }


        public ActionResult Index()
        {
            return View(db.AdminUsers.ToList());
        }

        //
        // GET: /AdminUser/Details/5

        public ActionResult Details(int id = 0)
        {
            AdminUser adminuser = db.AdminUsers.Find(id);
            if (adminuser == null)
            {
                return HttpNotFound();
            }
            return View(adminuser);
        }

        //
        // GET: /AdminUser/Create

        public ActionResult Create()
        {
            AdminUser adm = new AdminUser();
            return View(adm);
        }

        //
        // POST: /AdminUser/Create

        [HttpPost]
        public ActionResult Create(AdminUser adminuser)
        {
            if (ModelState.IsValid)
            {
                db.AdminUsers.Add(adminuser);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(adminuser);

            //using (BSSDbContext db = new BSSDbContext())
            //{
            // AdminUser Adm = db.AdminUsers.FirstOrDefault(ad => ad.UserName.ToLower() == adminuser.UserName.ToLower());

            //    // Check if Agent already exists
            //    if (Adm == null)
            //    {
            //        // Insert name into the profile table
            //        db.AdminUsers.Add(new AdminUser { UserName = adminuser.UserName });
            //        db.SaveChanges();
            //        return RedirectToAction("Index");

            //    }
            //    else
            //    {
            //        ModelState.AddModelError("UserName", "User name already exists. Please enter a different User name.");
            //    }
            //}
            //return View(adminuser);

        }

        //
        // GET: /AdminUser/Edit/5

        public ActionResult Edit(int id = 0)
        {
            AdminUser adminuser = db.AdminUsers.Find(id);
            if (adminuser == null)
            {
                return HttpNotFound();
            }
            return View(adminuser);
        }

        //
        // POST: /AdminUser/Edit/5

        [HttpPost]
        public ActionResult Edit(AdminUser adminuser)
        {
            if (ModelState.IsValid)
            {
                db.Entry(adminuser).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(adminuser);
        }

        //
        // GET: /AdminUser/Delete/5

        public ActionResult Delete(int id = 0)
        {
            AdminUser adminuser = db.AdminUsers.Find(id);
            if (adminuser == null)
            {
                return HttpNotFound();
            }
            return View(adminuser);
        }

        //
        // POST: /AdminUser/Delete/5

        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {
            AdminUser adminuser = db.AdminUsers.Find(id);
            db.AdminUsers.Remove(adminuser);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

BSS/Controllers/AgentDetailsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using BSS.Models;
using PagedList;

namespace BSS.Controllers
{
    [Authorize]
    public class AgentDetailsController : Controller
    {
        private BSSDbContext db = new BSSDbContext();

        //
        // GET: /AgentDetails/

        public ActionResult Index(string sortOrder, int? page)
        {
            ViewBag.CurrentSort = sortOrder;
            var agent = from s in db.AgentDetails
                        select s;
            switch (sortOrder)
            {
                case "Name_desc":
                    agent = agent.OrderByDescending(s => s.AgentId);
                    break;
                default:
                    agent = agent.OrderBy(s => s.AgentId);
                    break;
            }
            //page = 1;
            int pageSize = 15;
            int pageNumber = (page ?? 1);
            return View(agent.ToPagedList(pageNumber, pageSize));
        }

        //
        // GET: /AgentDetails/Details/5

        public ActionResult Details(int id = 0)
        {
            AgentDetails agentdetails = db.AgentDetails.Find(id);
            if (agentdetails == null)
            {
                return HttpNotFound();
            }
            return View(agentdetails);
        }

        //
        // GET: /AgentDetails/Create

        public ActionResult Create()
        {
            return View();
        }

        //
        // POST: /AgentDetails/Create

        [HttpPost]
        public ActionResult Create(AgentDetails agentdetails)
        {
            //if (ModelState.IsValid)
            //{
            //    db.AgentDetails.Add(agentdetails);
            //    db.SaveChanges();
            //    return RedirectToAction("Index");
            //}

            //return View(agentdetails);

            using (BSSDbContext db = new BSSDbContext())
            {
                AgentDetails Agent = db.AgentDetails.FirstOrDefault(a => a.AgentName.ToLower() == agentdetails.AgentName.ToLower());

                // Check if Agent already exists
                if (Agent == null)
                {
                    // Insert name into the profile table
                    db.AgentDetails.Add(new AgentDetails { AgentName = agentdetails.AgentName });
                    db.SaveChanges();
                    return RedirectToAction("Index");

                }
                else
                {
                    ModelState.AddModelError("AgentName", "Agent name already exists. Please enter a different Agent name.");
                }
            }
            return View(agentdetails);
        }

        //
        // GET: /AgentDetails/Edit/5

        public ActionResult Edit(int id = 0)
        {
            AgentDetails agentdetails = db.AgentDetails.Find(id);
            if (agentdetails == null)
            {
                return HttpNotFound();
            }
            return View(agentdetails);
        }

        //
        // POST: /AgentDetails/Edit/5

        [HttpPost]
        public ActionResult Edit(AgentDetails agentdetails)
        {
            if (ModelState.IsValid)
            {
                db.Entry(agentdetails).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(agentdetails);
        }

        //
        // GET: /AgentDetails/Delete/5

        public ActionResult Delete(int id = 0)
        {
            AgentDetails agentdetails = db.AgentDetails.Find(id);
            if (agentdetails == null)
            {
                return HttpNotFound();
            }
            return View(agentdetails);
        }

        //
        // POST: /AgentDetails/Delete/5

        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {
            AgentDetails agentdetails = db.AgentDetails.Find(id);
            db.AgentDetails.Remove(agentdetails);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

BSS/Controllers/LoginController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Transactions;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using DotNetOpenAuth.AspNet;
using Microsoft.Web.WebPages.OAuth;
using WebMatrix.WebData;
using BSS.Filters;
using BSS.Models;
using System.Data.Entity;
using System.Data;

namespace BSS.Controllers
{
    public class LoginController : Controller
    {
        private BSSDbContext db = new BSSDbContext();

        //
        // GET: /Login/


        public ActionResult Welcome()
        {
            return View();
        }


        public ActionResult Index()
        {
            return View(db.Logins.ToList());
        }

        //
        // GET: /Login/Details/5

        public ActionResult Details(int id = 0)
        {
            Login login = db.Logins.Find(id);
            if (login == null)
            {
                return HttpNotFound();
            }
            return View(login);
        }

        //
        // GET: /Login/Create

        public ActionResult Create()
        {
            // ViewBag.ReturnUrl = returnUrl;
          //  ViewBag.UserTypes = db.UserTypes.ToList();
            return View();
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(User model, string returnUrl)
        {
            // Lets first check if the Model is valid or not
            if (ModelState.IsValid)
            {
                using (BSSDbContext db = new BSSDbContext())
                {
                    if (db.Logins == null)
                    {
                        if (ModelState.IsValid)
                        {

                            if (model.UserName == "Admin" && model.Password == "1234")
                            {
                                FormsAuthentication.SetAuthCookie(model.UserName, false);
                                return RedirectToAction("About", "Home");
                            }
                            {
                                ModelState.AddModelError("", "Invalid Username or Password");
                            }
                        }

                        return View(model);

                    }
                    else
                    {
                        string username = model.UserName;
                        string password = model.Password;



                        bool userValid = db.Logins.Any(user => user.UserName == username && user.Password == password);


                        if (userValid)
                        {

                            FormsAuthentication.SetAuthCookie(username, false);
                            if (Url.IsLocalUrl(returnUrl) && returnUrl.Length > 1 && returnUrl.StartsWith("/")
                                && !returnUrl.StartsWith("//") && !returnUrl.StartsWith("/\\"))
                            {
                                return Redirect(returnUrl);
                            }
                            else
                            {
                                return RedirectToAction("Index1", "BookingReceived");
                            }
                        }
                        else
                        {
                            // ViewBag.UserTypes = db.UserTypes.ToList();
                            ModelState.AddModelError("", "Enter Valid UserName and Password");
                        }
                    }
                }
            }

            // If we got this far, something failed, redisplay form
            return View(model);
        }


        public ActionResult Create1()
        {
            // ViewBag.ReturnUrl = returnUrl;
            //  ViewBag.UserTypes = db.UserTypes.ToList();
            return View();
        }


        [HttpPost]
        public ActionResult Create1(Login login)
        {
            if (ModelState.IsValid)
            {
                db.Logins.Add(login);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(login);

            //using (BSSDbContext db = new BSSDbContext())
            //{
            //    Login lg = db.Logins.FirstOrDefault(l => l.UserName.ToLower() == login.UserName.ToLower());

            //    // Check if Agent already exists
            //    if (lg == null)
            //    {
            //        // Insert name into the profile table
            //        db.Logins.Add(new Login { UserName = login.UserName });
            //        db.SaveChanges();
            //        return RedirectToAction("Index");

            //    }
            //    else
            //    {
            //        ModelState.AddModelError("UserName", "User name already exists. Please enter a different User name.");
            //    }
            //}
            //return View(login);
        }


        public ActionResult Register()
        {
            ViewBag.UserTypes = db.UserTypes.ToList();
            return View();
        }



        [HttpPost]
        public ActionResult Register(Login login)
        {
            if (ModelState.IsValid)
            {
                db.Logins.Add(login);
                db.SaveChanges();
                // return RedirectToAction("Index");
            }

            return View(login);
        }


        public ActionResult Edit(int id = 0)
        {
            Login login = db.Logins.Find(id);
            if (login == null)
            {
                return HttpNotFound();
            }
            return View(login);
        }

        //
        // POST: /Login/Edit/5

        [HttpPost]
        public ActionResult Edit(Login login)
        {
            if (ModelState.IsValid)
            {
                db.Entry(login).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(login);
        }

        //
        // GET: /Login/Delete/5

        public ActionResult Delete(int id = 0)
        {
            Login login = db.Logins.Find(id);
            if (login == null)
            {
                return HttpNotFound();
            }
            return View(login);
        }

        //
        // POST: /Login/Delete/5

        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {
            Login login = db.Logins.Find(id);
            db.Logins.Remove(login);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }



        #region Logout
        public ActionResult Logout()
        {
            FormsAuthentication.SignOut();

            return RedirectToAction("Index", "Home");
        }
        #endregion


    }
}

BSS/Views/Shared/MainLogin.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <title>@ViewBag.Title - Booking Status</title>
    <link href="~/favicon.ico" rel="shortcut icon" type="image/x-icon" />
    <meta name="viewport" content="width=device-width" />
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <link href="@Url.Content("~/Content/Site.css")" rel="stylesheet" type="text/css" />
    <link href="../../Content/themes/base/jquery.ui.all.css" rel="stylesheet" type="text/css" />
    <script src="@Url.Content("~/Scripts/jquery-1.5.1.min.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/jquery-ui-1.8.11.js")" type="text/javascript"></script>
    
</head>


<body>
    <div class="page">
        <div id="header">
    @*     <div id="title">
         <img src = "@Url.Content("~/Images/ExploreGlobal.jpg")" class="img-respensoive" alt="img-responsive"/> <br />
              
            </div>
            <br />*@

           

         @*   <div id="logindisplay">
                @if (Request.IsAuthenticated)
                {
                    <text>Welcome <strong>@User.Identity.Name</strong>! [ @Html.ActionLink("Logout", "Create", "Login")
                    ]</text>
                }
                else
                {

                }
            </div>*@
             
             <div id="logindisplay">
               
               @Html.ActionLink("Login", "Create", "Login") 
               

            </div>

            <div id="menucontainer" align="center" >
                <ul id="menu">
               @*   <section id="login">
                        @Html.Partial("_LoginPartial")
                    </section>
                   @* <li>@Html.ActionLink("Login Form", "Create", "Login")</li>
                    <li>@Html.ActionLink("Current BookingStatus", "Index1", "BookingArrived")</li>*@
                </ul>
            </div>
        
        </div>
   
    <div id="main">
     @Scripts.Render("~/bundles/jquery")
        @RenderSection("featured", required: false)
        <section>
           <div>
         <img src = "@Url.Content("~/Images/ExploreGlobal.jpg")" class="img-respensoive" alt="img-responsive"/> <br />
            </div>
            @RenderBody()
              <br />
   <br />
        </section>
    </div>
  
    <div id="footer">
        <div class="content-wrapper">
            <div class="float-left">
                <p>
                    &copy; @DateTime.Now.Year - ExploreGlobal</p>
            </div>
        </div>
    </div>

   @* @Scripts.Render("~/bundles/jquery")*@
    @RenderSection("scripts", required: false)
     </div>
</body>
</html>

BSS/Views/Shared/PendingLayoutPage.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <title>@ViewBag.Title - Live Update</title>
    <link href="~/favicon.ico" rel="shortcut icon" type="image/x-icon" />
    <meta name="viewport" content="width=device-width" />
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <link href="@Url.Content("~/Content/Site.css")" rel="stylesheet" type="text/css" />
    <link href="../../Content/themes/base/jquery.ui.all.css" rel="stylesheet" type="text/css" />
    <script src="@Url.Content("~/Scripts/jquery-1.5.1.min.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/jquery-ui-1.8.11.js")" type="text/javascript"></script>
</head>

<body>
    <div class="page">
        <div id="header">
            <div id="logindisplay">
                @Html.ActionLink("Login", "Login", "AdminUser")
                @Html.ActionLink("Home", "Create", "Login")
            </div>
              <div id="menucontainer">
                <ul id="menu2">
               
                   @* <li>@Html.ActionLink("Live Update", "Index1", "BookingArrived")</li>
                    <li>@Html.ActionLink("Pending Enquiries", "Pending", "BookingArrived")</li>*@

                      <li>@Html.ActionLink("Live Update", "Index1", "BookingReceived")</li>
                    <li>@Html.ActionLink("Pending Enquiries", "Pending", "BookingReceived")</li>
                 
                </ul>
            </div>
        </div>
      
        <div id="main">
            @Scripts.Render("~/bundles/jquery")
            @RenderSection("featured", required: false)

    <div class="newtable-responsive">
        <table style="border: none  0px white;">
        <tr>
        <td style="border: none  0px white;"> <img src = "@Url.Content("~/Images/ExploreGlobal.jpg")" class="img-respensoive" alt="img-responsive"/></td>
        <td style="padding:0px 200px 0px 200px; border: none  0px white;"> <h1> PENDING ENQUIRIES </h1></td>
        </tr>
        </table>
        </div>
        <br />
            @RenderBody()
                <br />
                <br />
                <br />
                <br />
                <br />
                <br />
                <br />
                <br />
                <br />
                <br />
                <br />
                <br />
                <br />
                <br />
        </div>
        <div id="footer">
            <div class="content-wrapper">
                <div class="float-left">
                    <p>
                        &copy; @DateTime.Now.Year - ExploreGlobal</p>
                </div>
            </div>
        </div>
        @* @Scripts.Render("~/bundles/jquery")*@
        @RenderSection("scripts", required: false)
    </div>
</body>
</html>

BSS/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    @*<meta http-equiv="refresh" content="30">*@ <title>@ViewBag.Title - Booking Status
    </title>
    <link href="~/favicon.ico" rel="shortcut icon" type="image/x-icon" />
    <meta name="viewport" content="width=device-width" />
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <link href="@Url.Content("~/Content/Site.css")" rel="stylesheet" type="text/css" />
    <link href="../../Content/themes/base/jquery.ui.all.css" rel="stylesheet" type="text/css" />
    <script src="@Url.Content("~/Scripts/jquery-1.5.1.min.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/jquery-ui-1.8.11.js")" type="text/javascript"></script>
    <script type="text/javascript">
        $.ajaxSetup({ cache: false });

        $(document).ready(function () {
            $(".openDialog").live("click", function (e) {
                e.preventDefault();

                $("<div></div>")
                    .addClass("dialog")
                    .attr("id", $(this)
                    .attr("data-dialog-id"))
                    .appendTo("body")
                    .dialog({
                        title: $(this).attr("data-dialog-title"),
                        close: function () { $(this).remove(); },
                        modal: true,
                        height: 250,
                        width: 900,
                        left: 0

                    })
                    .load(this.href);
            });

            $(".close").live("click", function (e) {
                e.preventDefault();
                $(this).closest(".dialog").dialog("close");
            });
        });

        $(function () {
            $("body ul li").each(function () {
                if ($(this).find("ul").length > 0) {

                    //show subnav on hover  
                    $(this).mouseenter(function () {
                        $(this).find("ul").stop(true, true).slideDown();
                    });

                    //hide submenus on exit  
                    $(this).mouseleave(function () {
                        $(this).find("ul").stop(true, true).slideUp();
                    });

                    $(this).find("ul").mousemove(function () {
                        $(this).stop(true, true).show();
                    });
                }
            });
        });

        $(function () {
            $('.menu ul li').hover(
function () {
    $('.sub_menu', this).stop(true, true).slideDown(); /*slideDown the subitems on mouseover*/
}, function () {
    $('.sub_menu', this).stop(true, true).slideUp();  /*slideUp the subitems on mouseout*/
});
        });
    </script>
    <style>

body ul ul {
    display: none;
    position:absolute;
    width: 95%;
    background: #5C87B2;
    border-top: 2px solid #5C87B2;;
    filter:alpha(opacity=80);
    -moz-opacity:0.8;
    -khtml-opacity: 0.8;
    opacity: 0.8;
}
body ul ul li{
    line-height: 1.1em;
}
</style>
</head>
<body>
    <div class="page">
        <div id="header">
            <div id="title">
                <img src = "@Url.Content("~/Images/ExploreGlobal.jpg")" class="img-respensoive" alt="img-responsive" />
                <br />
                @*<h1>Booking Status</h1>*@
            </div>
            <br />
            <div id="logindisplay">
                @if (Request.IsAuthenticated)
                {
                    <text>Welcome <strong>@User.Identity.Name</strong>! [ @Html.ActionLink("Logout", "Index1", "BookingReceived")
                    ]</text>
                }
                else
                {

                }
            </div>
            <br />
            <div id="menucontainer">
                <ul id="menu">
                    <li>@Html.ActionLink("User", "Index", "Login")</li>
                    <li>@Html.ActionLink("Admin Details", "Index", "AdminUser")</li>
                    <li>@Html.ActionLink("Agent Details", "Index", "AgentDetails")</li>
                    <li>@Html.ActionLink("Consultant Details", "Index", "ConsultantDetails")</li>
                    <li>@Html.ActionLink("Hotel Details", "Index", "HotelDetails")</li>
                   @* <li>@Html.ActionLink("Booking Arrived", "Index", "BookingArrived")</li>*@
                    <li>@Html.ActionLink("Booking Received", "Index", "BookingReceived")
                   @* <li>@Html.ActionLink("Report","Report","BookingArrived")
                    <div class="sub_menu">
                        <ul>
                            <li>@Html.ActionLink("Overall Report", "Report", "BookingArrived")</li>
                            <li>@Html.ActionLink("DateWise", "ReportViewer", "BookingArrived")</li>
                            <li>@Html.ActionLink("Date&BookingStatusWise", "ReportViewer1", "BookingArrived") </li>
                            <li>@Html.ActionLink("Date&AgentWise", "ReportViewerDateAgentWise", "BookingArrived") </li>
                            <li>@Html.ActionLink("Date&ConsultantWise", "ReportViewerDateConsultantWise", "BookingArrived") </li>
                            <li>@Html.ActionLink("Date&HotelWise", "ReportViewerDateHotelWise", "BookingArrived") </li>
                           @* <li>@Html.ActionLink("By Date", "ReportViewer", "BookingArrived") </li>
                        </ul>
                    </div>
                    </li>*@
                       <li>@Html.ActionLink("Report","Report","BookingReceived")
                    <div class="sub_menu">
                        <ul>
                            <li>@Html.ActionLink("Overall Report", "Report", "BookingReceived")</li>
                            <li>@Html.ActionLink("DateWise", "ReportViewer", "BookingReceived")</li>
                            <li>@Html.ActionLink("Date&BookingStatusWise", "ReportViewer1", "BookingReceived") </li>
                            <li>@Html.ActionLink("Date&AgentWise", "ReportViewerDateAgentWise", "BookingReceived") </li>
                            <li>@Html.ActionLink("Date&ConsultantWise", "ReportViewerDateConsultantWise", "BookingReceived") </li>
                            <li>@Html.ActionLink("Date&HotelWise", "ReportViewerDateHotelWise", "BookingReceived") </li>
                           @* <li>@Html.ActionLink("By Date", "ReportViewer", "BookingArrived") </li>*@
                        </ul>
                    </div>
                    </li>
                </ul>
            </div>
        </div>
        <div id="main">
            @Scripts.Render("~/bundles/jquery")
            @RenderSection("featured", required: false)
            @RenderBody()
            <br />
            <br />
        </div>
        <div id="footer">
            <div class="float-left">
                <b>
                    <p>
                        &copy; @DateTime.Now.Year - Explore Global</p>
                </b>
            </div>
        </div>
        @* @Scripts.Render("~/bundles/jquery")*@
        @RenderSection("scripts", required: false)
    </div>
</body>
</html>